const express = require('express')
const router = express.Router()

const publicController = require('../controllers/publicController')
const userController = require('../controllers/UserController')
const propostaController = require('../controllers/propostaController')
const auth = require('../middlewares/auth')
const verifyToken = require('../middlewares/verifyToken')


router.get('/verifyToken', auth, verifyToken.verify)

router.get('/', publicController.index)
router.post('/login', publicController.login)
router.post('/logout', publicController.logout)

router.get('/user', userController.index)

router.post('/upload', propostaController.upload)
router.get('/show', propostaController.show)
router.get('/naoRealizadas', propostaController.buscarPropostasNaoRealizadas)
router.get('/proposta/:id', propostaController.mostrarPropostaPorId)
router.put('/agendar', propostaController.agendar)
router.put('/reagendar', propostaController.reagendar)
router.put('/cancelar', propostaController.cancelar)
router.delete('/delete/:id', propostaController.delete)
router.put('/alterarTelefone', propostaController.alterarTelefone)
router.get('/naoAgendadas', propostaController.naoAgendadas)
router.get('/agendadas', propostaController.agendadas)
router.put('/alterarVigencia', propostaController.alterarVigencia)
router.put('/alterarFormulario', propostaController.alterarFormulario)
router.put('/alterarSexo', propostaController.alterarSexo)
router.put('/voltarEntrevista', propostaController.voltarEntrevista)
router.put('/tentativaContato', propostaController.tentativaContato)
router.put('/concluir', propostaController.concluir)
router.get('/naoEnviadas', propostaController.naoEnviadas)
router.get('/ajustar', propostaController.propostasAAjustar)
router.put('/ajustar', propostaController.ajustarCpf)
router.put('/enviarMensagem', propostaController.enviarMensagem)
router.get('/situacao/:situacao', propostaController.situacao)
router.get('/janelasEscolhidas', propostaController.janelasEscolhidas)
router.get('/erroMensagem', propostaController.problemaEnviar)
router.get('/atendimentoHumanizado', propostaController.atendimentoHumanizado)
router.get('/chat/:whatsapp', propostaController.chat)
router.get('/conversas/:pesquisa', propostaController.conversas)
router.get('/gerarMensagens', propostaController.gerarMensagens)
router.get('/naoRealizadas', propostaController.naoRealizadas)
router.put('/voltarAjuste', propostaController.voltarAjuste)
router.put('/mandarAtendimentoHumanizado', propostaController.mandarAtendimentoHumanizado)
router.post('/sendMessage', propostaController.mandarMensagem)
router.put('/encerrarAtendimento', propostaController.encerrarAtendimentoJanela)
router.put('/encerrarHumanizado', propostaController.encerrarHumanizado)
router.put('/assumirConversa', propostaController.assumirAtendimento)
router.put('/visualizarMensagem', propostaController.visualizarMensagem)
router.put('/reenviarMensagens', propostaController.reenviarMensagens)
router.post('/lembreteMensagem', propostaController.lembreteMensagem)

router.post('/receiveMessage', propostaController.mensagemRecebida)

router.post('/migrarBanco', propostaController.migrarBanco)
router.get('/cancelarPropostasEmMassa', propostaController.cancelarPropostasEmMassa)

router.get('/testeio', propostaController.testeIo)

router.get('/teste', propostaController.testeMensagem)

module.exports = router